FROM osrf/ros:humble-desktop-full

SHELL [ "/bin/bash","-c" ]

# Environment variables
ENV ROS_DISTRO=humble
ENV DEBIAN_FRONTEND=noninteractive

# INSTALLING PKGS

## Setup virutal env 
RUN mkdir /opt/venv && \
    apt update && apt upgrade -y && \
    apt install python3-virtualenv -y && \
    virtualenv /opt/venv && \
    export PATH=/opt/venv/bin:$PATH

## Install Basic Tools
RUN apt install \
    nano \
    curl \
    tmux \
    ros-dev-tools \
    -y

## Install Simulation tools
RUN apt install \
    gazebo \
    ignition-fortress \
    -y

## Install visualization tools(rviz2 already installed)
RUN apt install \
    ros-$ROS_DISTRO-rviz2 \
    ~nros-$ROS_DISTRO-rqt* \
    -y

## Install ros2_control
RUN apt install -y \
    ros-$ROS_DISTRO-ros2-control \
    ros-$ROS_DISTRO-ros2-controllers \
    ros-$ROS_DISTRO-gazebo-ros2-control
    
## Install localization pkgs
RUN apt install -y \
    ros-$ROS_DISTRO-robot-localization 

## Install nav2
RUN apt update && \
    apt install -y \
    ros-$ROS_DISTRO-navigation2 \
    ros-$ROS_DISTRO-nav2-bringup 

## Install examples
RUN apt update && \
    apt install -y \
    ros-$ROS_DISTRO-turtlebot3*


# SOURCING PKGS

## adding source to bashrc
RUN echo 'source /opt/ros/$ROS_DISTRO/setup.bash' >> ~/.bashrc && \
    echo 'export PATH=/opt/venv/bin:$PATH' >> ~/.bashrc && \
    echo 'source /usr/share/gazebo/setup.bash' >> ~/.bashrc && \
    echo 'source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash' >> ~/.bashrc


# DEPENDENCIES

## Colcon build requirements
RUN /opt/venv/bin/pip install \
    catkin_pkg \
    empy==3.3.4 \
    lark 

## rqt through ros2
RUN /opt/venv/bin/pip install \
    PyQt5 PySide2 pydot

## nav2
RUN /opt/venv/bin/pip install \
    numpy lxml

## rqt
RUN /opt/venv/bin/pip3 install \
    pyyaml packaging netifaces