FROM osrf/ros:humble-desktop-full

# INSTALLING PKGS

## Setup virutal env 
RUN mkdir /opt/venv && \
    apt update && apt upgrade -y && \
    apt install -y \
    python3-pip && \
    pip install virtualenv && \
    virtualenv /opt/venv && \
    export PATH="/opt/venv/bin:$PATH"

## Install Basic Tools
RUN apt update && \
    apt install -y \
    nano \
    curl \
    tmux \
    ros-dev-tools

## Install ros2 tools
RUN apt update && \
    apt install -y \
    gazebo \
    ignition-fortress \
    ~nros-humble-rqt*

## Install ros2_control
RUN apt update && \
    apt install -y \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-gazebo-ros2-control
    
## Install localization pkgs
RUN apt update && \
    apt install -y \
    ros-humble-robot-localization 

## Install nav2
RUN apt update && \
    apt install -y \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup 

## Install examples
RUN apt update && \
    apt install -y \
    ros-humble-turtlebot3*


# SOURCING PKGS

## adding source to bashrc
RUN echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc && \
    echo 'export PATH=/opt/venv/bin:$PATH' >> ~/.bashrc && \
    echo 'source /usr/share/gazebo/setup.bash' >> ~/.bashrc && \
    echo 'source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash' >> ~/.bashrc


# DEPENDENCIES

## Colcon build requirements
RUN /opt/venv/bin/pip install \
    catkin_pkg \
    empy==3.3.4 \
    lark 

## rqt through ros2
RUN /opt/venv/bin/pip install \
    PyQt5 PySide2 pydot

## nav2
RUN /opt/venv/bin/pip install \
    numpy lxml

## rqt
RUN /opt/venv/bin/pip3 install \
    pyyaml packaging 

